/**
 * ITEMS DATABASE
 * Catálogo centralizado de todos os itens do jogo
 * 
 * Tipos: Arma, Armadura, Escudo, Poção, Material, Gema, Artefato, Consumível
 * Raridades: common, uncommon, rare, epic, unique
 */

// ===== WEAPONS (Armas) =====
const WEAPONS = [
    // --- Two-Hand Swords (Base PoE2) ---
    {
        id: 'corroded_longsword',
        name: 'Espada Corroída',
        type: 'Arma',
        subtype: 'Espada',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 50,
        description: 'Uma lâmina gasta pelo tempo. Ainda corta.',
        damage: { min: 9, max: 16, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.3,
        requirements: { level: 1, str: 0, dex: 0 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'iron_greatsword',
        name: 'Montante de Ferro',
        type: 'Arma',
        subtype: 'Espada',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 120,
        description: 'Ferro forjado em uma lâmina robusta e confiável.',
        damage: { min: 13, max: 23, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.35,
        requirements: { level: 6, str: 9, dex: 9 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'blessed_claymore',
        name: 'Claymore Abençoada',
        type: 'Arma',
        subtype: 'Espada',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 280,
        description: 'Benzida por sacerdotes. Brilha levemente na escuridão.',
        damage: { min: 19, max: 32, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.3,
        requirements: { level: 11, str: 14, dex: 14 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'broad_greatsword',
        name: 'Montante Largo',
        type: 'Arma',
        subtype: 'Espada',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 420,
        description: 'Lâmina larga que parte armaduras com facilidade.',
        damage: { min: 25, max: 42, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.25,
        requirements: { level: 16, str: 19, dex: 19 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'rippled_greatsword',
        name: 'Montante Ondulado',
        type: 'Arma',
        subtype: 'Espada',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 650,
        description: 'Padrão ondulado na lâmina aumenta o corte.',
        damage: { min: 28, max: 52, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.3,
        requirements: { level: 22, str: 24, dex: 24 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'arced_longsword',
        name: 'Espada Longa Arqueada',
        type: 'Arma',
        subtype: 'Espada',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 850,
        description: 'Curvatura sutil permite golpes devastadores.',
        damage: { min: 31, max: 58, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.35,
        requirements: { level: 28, str: 29, dex: 29 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'stone_greatsword',
        name: 'Montante de Pedra',
        type: 'Arma',
        subtype: 'Espada',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 1100,
        description: 'Forjada com minério de pedra mística. Extremamente pesada.',
        damage: { min: 40, max: 67, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.3,
        requirements: { level: 33, str: 34, dex: 34 },
        stackable: false,
        slot: 'weapon',
        bonusStats: { def: 5 }
    },
    {
        id: 'obsidian_greatsword',
        name: 'Montante de Obsidiana',
        type: 'Arma',
        subtype: 'Espada',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 1500,
        description: 'Vidro vulcânico negro. Afiada como nenhuma outra.',
        damage: { min: 49, max: 73, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.25,
        requirements: { level: 36, str: 37, dex: 37 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'keen_greatsword',
        name: 'Montante Afiada',
        type: 'Arma',
        subtype: 'Espada',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 2200,
        description: 'Afiada ao extremo. Pode cortar através de escudos.',
        damage: { min: 45, max: 94, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.3,
        requirements: { level: 45, str: 45, dex: 45 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'ancient_greatblade',
        name: 'Lâmina Antiga',
        type: 'Arma',
        subtype: 'Espada',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 2800,
        description: 'Artefato de uma era esquecida. Gravuras brilham fracamente.',
        damage: { min: 55, max: 103, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.25,
        requirements: { level: 49, str: 49, dex: 49 },
        stackable: false,
        slot: 'weapon',
        bonusStats: { vig: 5 }
    },
    {
        id: 'flanged_greatblade',
        name: 'Lâmina Flangeada',
        type: 'Arma',
        subtype: 'Espada',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 3100,
        description: 'Lâmina serrilhada causa ferimentos horríveis.',
        damage: { min: 51, max: 106, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.3,
        requirements: { level: 52, str: 51, dex: 51 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'regalia_longsword',
        name: 'Espada Longa Régia',
        type: 'Arma',
        subtype: 'Espada',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 4000,
        description: 'Carregada pela realeza. Emblemas de ouro adornam a guarda.',
        damage: { min: 61, max: 92, type: 'physical' },
        crit: 6,
        attackPerSecond: 1.35,
        requirements: { level: 54, str: 53, dex: 53 },
        stackable: false,
        slot: 'weapon',
        bonusStats: { str: 10 }
    },
    {
        id: 'ultra_greatsword',
        name: 'Ultra Montante',
        type: 'Arma',
        subtype: 'Espada',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 5500,
        description: 'Uma lâmina tão grande que desafia a lógica. Para os mais fortes.',
        damage: { min: 72, max: 119, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.3,
        requirements: { level: 65, str: 63, dex: 63 },
        stackable: false,
        slot: 'weapon',
        bonusStats: { str: 15 }
    },

    // --- Two-Hand Axes & Polearms (Base PoE2) ---
    {
        id: 'splitting_greataxe',
        name: 'Machado Grande Rachador',
        type: 'Arma',
        subtype: 'Machado',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 40,
        description: 'Lâmina pesada projetada para rachar escudos e ossos.',
        damage: { min: 8, max: 20, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.20,
        requirements: { level: 1, str: 0, dex: 0 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'light_halberd',
        name: 'Alabarda Leve',
        type: 'Arma',
        subtype: 'Alabarda',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 80,
        description: 'Alabarda balanceada para golpes rápidos.',
        damage: { min: 10, max: 25, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.25,
        requirements: { level: 4, str: 9, dex: 0 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'executioner_greataxe',
        name: 'Machado Grande de Carrasco',
        type: 'Arma',
        subtype: 'Machado',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 180,
        description: 'Usado em execuções públicas. Manchas escuras cobrem a lâmina.',
        damage: { min: 10, max: 41, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.20,
        requirements: { level: 10, str: 17, dex: 9 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'arced_greataxe',
        name: 'Machado Grande Arqueado',
        type: 'Arma',
        subtype: 'Machado',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 340,
        description: 'Curvatura na lâmina aumenta o poder de corte.',
        damage: { min: 17, max: 59, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.15,
        requirements: { level: 16, str: 25, dex: 12 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'elegant_glaive',
        name: 'Glaive Elegante',
        type: 'Arma',
        subtype: 'Alabarda',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 450,
        description: 'Lâmina longa montada em haste. Arte e letalidade em equilíbrio.',
        damage: { min: 19, max: 64, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.20,
        requirements: { level: 20, str: 30, dex: 14 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'savage_greataxe',
        name: 'Machado Grande Selvagem',
        type: 'Arma',
        subtype: 'Machado',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 620,
        description: 'Forjado por tribos bárbaras. Brutal e eficaz.',
        damage: { min: 23, max: 70, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.20,
        requirements: { level: 27, str: 39, dex: 17 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'rending_halberd',
        name: 'Alabarda Dilacerante',
        type: 'Arma',
        subtype: 'Alabarda',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 900,
        description: 'Lâmina serrilhada projetada para rasgar carne.',
        damage: { min: 27, max: 91, type: 'physical' },
        crit: 6.5,
        attackPerSecond: 1.20,
        requirements: { level: 33, str: 47, dex: 20 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'serrated_greataxe',
        name: 'Machado Grande Serrilhado',
        type: 'Arma',
        subtype: 'Machado',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 1300,
        description: 'Dentes de serra causam ferimentos devastadores.',
        damage: { min: 43, max: 99, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.15,
        requirements: { level: 40, str: 56, dex: 23 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'raider_glaive',
        name: 'Glaive de Saqueador',
        type: 'Arma',
        subtype: 'Alabarda',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 1700,
        description: 'Arma favorita de invasores nômades.',
        damage: { min: 43, max: 113, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.20,
        requirements: { level: 45, str: 63, dex: 26 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'ember_greataxe',
        name: 'Machado Grande de Brasa',
        type: 'Arma',
        subtype: 'Machado',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 2400,
        description: 'Imbuído com chamas eternas. Queima ao toque.',
        damage: { min: 58, max: 154, type: 'fire' },
        crit: 5,
        attackPerSecond: 1.20,
        requirements: { level: 50, str: 70, dex: 28 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'ceremonial_halberd',
        name: 'Alabarda Cerimonial',
        type: 'Arma',
        subtype: 'Alabarda',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 2200,
        description: 'Carregada por guardas de honra. Decorada com runas.',
        damage: { min: 53, max: 123, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.20,
        requirements: { level: 52, str: 72, dex: 29 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'monumental_greataxe',
        name: 'Machado Grande Monumental',
        type: 'Arma',
        subtype: 'Machado',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 2600,
        description: 'Tamanho colossal. Requer força titânica para empunhar.',
        damage: { min: 48, max: 143, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.20,
        requirements: { level: 57, str: 79, dex: 32 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'vile_greataxe',
        name: 'Machado Grande Vil',
        type: 'Arma',
        subtype: 'Machado',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 3200,
        description: 'Corrompido por magia negra. Pulsa com energia sinistra.',
        damage: { min: 59, max: 155, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.20,
        requirements: { level: 65, str: 89, dex: 36 },
        stackable: false,
        slot: 'weapon'
    },

    // --- Two-Hand Maces (Maças de Duas Mãos - Base PoE2) ---
    {
        id: 'felled_greatclub',
        name: 'Clava Abatida',
        type: 'Arma',
        subtype: 'Maça',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 45,
        description: 'Tronco arrancado e moldado. Primitivo, mas letal.',
        damage: { min: 13, max: 18, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.1,
        requirements: { level: 1, str: 0, dex: 0 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'oak_greathammer',
        name: 'Martelo de Carvalho',
        type: 'Arma',
        subtype: 'Maça',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 90,
        description: 'Madeira densa com cabeça de ferro.',
        damage: { min: 14, max: 26, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.05,
        requirements: { level: 4, str: 11, dex: 0 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'forge_maul',
        name: 'Malho de Forja',
        type: 'Arma',
        subtype: 'Maça',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 200,
        description: 'Ferramenta de ferreiro transformada em arma.',
        damage: { min: 29, max: 39, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.05,
        requirements: { level: 11, str: 23, dex: 0 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'studded_greatclub',
        name: 'Clava Tachoada',
        type: 'Arma',
        subtype: 'Maça',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 320,
        description: 'Pregos de ferro cravados aumentam o impacto.',
        damage: { min: 32, max: 48, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.1,
        requirements: { level: 16, str: 31, dex: 0 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'cultist_greathammer',
        name: 'Martelo Cultista',
        type: 'Arma',
        subtype: 'Maça',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 480,
        description: 'Usado em rituais profanos. Manchas escuras cobrem a superfície.',
        damage: { min: 32, max: 43, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.05,
        requirements: { level: 22, str: 41, dex: 0 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'temple_maul',
        name: 'Malho de Templo',
        type: 'Arma',
        subtype: 'Maça',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 720,
        description: 'Guardada em templos antigos. Gravuras sagradas brilham.',
        damage: { min: 35, max: 72, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.2,
        requirements: { level: 28, str: 52, dex: 0 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'leaden_greathammer',
        name: 'Martelo de Chumbo',
        type: 'Arma',
        subtype: 'Maça',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 1050,
        description: 'Peso brutal. Cada golpe sacode a terra.',
        damage: { min: 58, max: 78, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.1,
        requirements: { level: 33, str: 60, dex: 0 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'crumbling_maul',
        name: 'Malho Esfarelante',
        type: 'Arma',
        subtype: 'Maça',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 1350,
        description: 'Pedra antiga que se desintegra lentamente.',
        damage: { min: 62, max: 75, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.1,
        requirements: { level: 38, str: 68, dex: 0 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'pointed_maul',
        name: 'Malho Pontiagudo',
        type: 'Arma',
        subtype: 'Maça',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 1900,
        description: 'Ponta afiada para perfuração.',
        damage: { min: 68, max: 102, type: 'physical' },
        crit: 6.5,
        attackPerSecond: 1.1,
        requirements: { level: 45, str: 80, dex: 0 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'totemic_greatclub',
        name: 'Clava Totêmica',
        type: 'Arma',
        subtype: 'Maça',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 2300,
        description: 'Entalhes tribais cobrem a madeira endurecida.',
        damage: { min: 73, max: 99, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.1,
        requirements: { level: 50, str: 89, dex: 0 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'greatmace',
        name: 'Grande Maça',
        type: 'Arma',
        subtype: 'Maça',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 2550,
        description: 'A maça em sua forma mais pura e mortal.',
        damage: { min: 74, max: 124, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.1,
        requirements: { level: 52, str: 92, dex: 0 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'precise_greathammer',
        name: 'Martelo Preciso',
        type: 'Arma',
        subtype: 'Maça',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 2750,
        description: 'Balanceamento perfeito para golpes certeiros.',
        damage: { min: 87, max: 118, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.1,
        requirements: { level: 54, str: 96, dex: 0 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'giant_maul',
        name: 'Malho Gigante',
        type: 'Arma',
        subtype: 'Maça',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 3800,
        description: 'Tamanho descomunal. Apenas os mais fortes podem empunhar.',
        damage: { min: 96, max: 144, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.1,
        requirements: { level: 65, str: 114, dex: 0 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'snakewood_greathammer',
        name: 'Martelo de Madeira-Serpente',
        type: 'Arma',
        subtype: 'Maça',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 1900,
        description: 'Madeira exótica com padrão de escamas.',
        damage: { min: 59, max: 109, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.05,
        requirements: { level: 45, str: 80, dex: 0 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'blacksmith_maul',
        name: 'Malho de Ferreiro',
        type: 'Arma',
        subtype: 'Maça',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 2150,
        description: 'Forjado pelos mestres da bigorna.',
        damage: { min: 84, max: 113, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.05,
        requirements: { level: 48, str: 86, dex: 0 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'zealot_greathammer',
        name: 'Martelo Zelota',
        type: 'Arma',
        subtype: 'Maça',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 2400,
        description: 'Empunhado por fanáticos em cruzadas sangrentas.',
        damage: { min: 62, max: 83, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.05,
        requirements: { level: 51, str: 91, dex: 0 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'solemn_maul',
        name: 'Malho Solene',
        type: 'Arma',
        subtype: 'Maça',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 2750,
        description: 'Usado em cerimônias de execução.',
        damage: { min: 59, max: 123, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.2,
        requirements: { level: 54, str: 96, dex: 0 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'heavy_greathammer',
        name: 'Martelo Pesado',
        type: 'Arma',
        subtype: 'Maça',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 3100,
        description: 'Peso esmagador. Armaduras dobram sob seu impacto.',
        damage: { min: 94, max: 127, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.1,
        requirements: { level: 59, str: 104, dex: 0 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'disintegrating_maul',
        name: 'Malho Desintegrante',
        type: 'Arma',
        subtype: 'Maça',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 3400,
        description: 'Irradia energia entrópica.',
        damage: { min: 93, max: 114, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.1,
        requirements: { level: 62, str: 109, dex: 0 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'anvil_maul',
        name: 'Malho de Bigorna',
        type: 'Arma',
        subtype: 'Maça',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 4200,
        description: 'Forjado na própria bigorna. Peso monumental.',
        damage: { min: 112, max: 151, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.05,
        requirements: { level: 67, str: 134, dex: 0 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'sacred_maul',
        name: 'Malho Sagrado',
        type: 'Arma',
        subtype: 'Maça',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 5000,
        description: 'Abençoado por sacerdotes. Fulgor divino emana dele.',
        damage: { min: 76, max: 158, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.2,
        requirements: { level: 72, str: 149, dex: 0 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'ironwood_greathammer',
        name: 'Grande Martelo de Pau-Ferro',
        type: 'Arma',
        subtype: 'Maça',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 5500,
        description: 'Madeira petrificada mais dura que aço.',
        damage: { min: 94, max: 174, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.05,
        requirements: { level: 77, str: 163, dex: 0 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'massive_greathammer',
        name: 'Grande Martelo Maciço',
        type: 'Arma',
        subtype: 'Maça',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 6000,
        description: 'Peso esmagador. Cada golpe treme o chão.',
        damage: { min: 119, max: 161, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.10,
        requirements: { level: 77, str: 163, dex: 0 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'fanatic_greathammer',
        name: 'Grande Martelo Fanático',
        type: 'Arma',
        subtype: 'Maça',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 6200,
        description: 'Empunhado por devotos em batalhas santas.',
        damage: { min: 89, max: 120, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.05,
        requirements: { level: 78, str: 163, dex: 0 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'tawhoan_greatclub',
        name: 'Clava Grande Tawhoan',
        type: 'Arma',
        subtype: 'Maça',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 6400,
        description: 'Artefato tribal de guerreiros ancestrais.',
        damage: { min: 107, max: 145, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.10,
        requirements: { level: 78, str: 163, dex: 0 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'doom_maul',
        name: 'Malho da Ruína',
        type: 'Arma',
        subtype: 'Maça',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 6800,
        description: 'Imbuído com a essência da destruição absoluta.',
        damage: { min: 113, max: 138, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.10,
        requirements: { level: 79, str: 163, dex: 0 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'snakewood_greathammer',
        name: 'Martelo de Madeira-Serpente',
        type: 'Arma',
        subtype: 'Maça',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 1900,
        description: 'Madeira exótica com padrão de escamas.',
        damage: { min: 59, max: 109, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.05,
        requirements: { level: 45, str: 80, dex: 0 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'blacksmith_maul',
        name: 'Malho de Ferreiro',
        type: 'Arma',
        subtype: 'Maça',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 2150,
        description: 'Forjado pelos mestres da bigorna.',
        damage: { min: 84, max: 113, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.05,
        requirements: { level: 48, str: 86, dex: 0 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'zealot_greathammer',
        name: 'Martelo Zelota',
        type: 'Arma',
        subtype: 'Maça',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 2400,
        description: 'Empunhado por fanáticos em cruzadas sangrentas.',
        damage: { min: 62, max: 83, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.05,
        requirements: { level: 51, str: 91, dex: 0 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'solemn_maul',
        name: 'Malho Solene',
        type: 'Arma',
        subtype: 'Maça',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 2750,
        description: 'Usado em cerimônias de execução.',
        damage: { min: 59, max: 123, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.2,
        requirements: { level: 54, str: 96, dex: 0 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'heavy_greathammer',
        name: 'Martelo Pesado',
        type: 'Arma',
        subtype: 'Maça',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 3100,
        description: 'Peso esmagador. Armaduras dobram sob seu impacto.',
        damage: { min: 94, max: 127, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.1,
        requirements: { level: 59, str: 104, dex: 0 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'disintegrating_maul',
        name: 'Malho Desintegrante',
        type: 'Arma',
        subtype: 'Maça',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 3400,
        description: 'Irradia energia entrópica.',
        damage: { min: 93, max: 114, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.1,
        requirements: { level: 62, str: 109, dex: 0 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'anvil_maul',
        name: 'Malho de Bigorna',
        type: 'Arma',
        subtype: 'Maça',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 4200,
        description: 'Forjado na própria bigorna. Peso monumental.',
        damage: { min: 112, max: 151, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.05,
        requirements: { level: 67, str: 134, dex: 0 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'sacred_maul',
        name: 'Malho Sagrado',
        type: 'Arma',
        subtype: 'Maça',
        handType: 'Duas Mãos',
        rarity: 'common',
        value: 5000,
        description: 'Abençoado por sacerdotes. Fulgor divino emana dele.',
        damage: { min: 76, max: 158, type: 'physical' },
        crit: 5,
        attackPerSecond: 1.2,
        requirements: { level: 72, str: 149, dex: 0 },
        stackable: false,
        slot: 'weapon'
    },

    // --- Other Weapons (Legacy) ---
    {
        id: 'iron_sword',
        name: 'Espada de Ferro',
        type: 'Arma',
        subtype: 'Espada',
        rarity: 'common',
        value: 100,
        description: 'Uma espada simples, mas confiável.',
        stats: { atk: 5 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'warhammer',
        name: 'Martelo de Guerra',
        type: 'Arma',
        subtype: 'Martelo',
        rarity: 'uncommon',
        value: 300,
        description: 'Esmaga ossos e armaduras com facilidade.',
        stats: { atk: 12, spd: -2 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'battle_axe',
        name: 'Machado de Batalha',
        type: 'Arma',
        subtype: 'Machado',
        rarity: 'rare',
        value: 500,
        description: 'Uma lâmina pesada para guerreiros fortes.',
        stats: { atk: 15, str: 5 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'old_bow',
        name: 'Arco Velho',
        type: 'Arma',
        subtype: 'Arco',
        rarity: 'common',
        value: 12,
        description: 'Madeira gasta, mas ainda funcional.',
        stats: { atk: 2 },
        stackable: false,
        slot: 'weapon'
    },
    {
        id: 'corroded_sword',
        name: 'Espada Corroída',
        type: 'Arma',
        subtype: 'Espada',
        rarity: 'uncommon',
        value: 45,
        description: 'Ferrugem cobre a lâmina, mas ainda é afiada.',
        stats: { atk: 5 },
        stackable: false,
        slot: 'weapon'
    }
];

// ===== ARMOR (Armaduras e Escudos) =====
const ARMOR = [
    {
        id: 'iron_shield',
        name: 'Escudo de Ferro',
        type: 'Escudo',
        rarity: 'common',
        value: 80,
        description: 'Proteção básica contra golpes.',
        stats: { def: 5 },
        stackable: false,
        slot: 'offhand'
    },
    {
        id: 'chainmail',
        name: 'Cota de Malha',
        type: 'Armadura',
        rarity: 'uncommon',
        value: 250,
        description: 'Elos de aço entrelaçados para maior defesa.',
        stats: { def: 10, vig: 2 },
        stackable: false,
        slot: 'chest'
    }
];

// ===== CONSUMABLES (Poções, Elixires) =====
const CONSUMABLES = [
    {
        id: 'potion_small',
        name: 'Poção Pequena',
        type: 'Poção',
        rarity: 'common',
        value: 20,
        description: 'Recupera 20 pontos de vida.',
        stats: { heal: 20 },
        stackable: true,
        effect: 'heal'
    },
    {
        id: 'potion_medium',
        name: 'Poção Média',
        type: 'Poção',
        rarity: 'uncommon',
        value: 50,
        description: 'Recupera 50 pontos de vida.',
        stats: { heal: 50 },
        stackable: true,
        effect: 'heal'
    },
    {
        id: 'health_potion',
        name: 'Poção de Vida Menor',
        type: 'Poção',
        rarity: 'common',
        value: 50,
        description: 'Recupera 50 pontos de vida instantaneamente.',
        stats: { heal: 50 },
        stackable: true
    },
    {
        id: 'mana_potion',
        name: 'Poção de Mana Menor',
        type: 'Poção',
        rarity: 'common',
        value: 50,
        description: 'Restaura 30 pontos de mana.',
        stats: { mana: 30 },
        stackable: true
    },
    {
        id: 'elixir_strength',
        name: 'Elixir de Força',
        type: 'Elixir',
        rarity: 'uncommon',
        value: 150,
        description: '+5 Força por 10 minutos.',
        stats: { str: 5 },
        stackable: true,
        duration: 600 // seconds
    },
    {
        id: 'antidote',
        name: 'Antídoto',
        type: 'Consumível',
        rarity: 'common',
        value: 30,
        description: 'Cura envenenamento.',
        stats: {},
        stackable: true
    },
    {
        id: 'town_portal',
        name: 'Pergaminho de Portal',
        type: 'Consumível',
        rarity: 'rare',
        value: 200,
        description: 'Retorna para a vila instantaneamente.',
        stats: {},
        stackable: true
    }
];

// ===== MATERIALS (Materiais de Crafting) =====
const MATERIALS = [
    {
        id: 'coal',
        name: 'Carvão',
        type: 'Material',
        rarity: 'common',
        value: 5,
        description: 'Combustível essencial para a forja. Queima com chamas intensas.',
        stackable: true
    },
    {
        id: 'leather',
        name: 'Couro',
        type: 'Material',
        rarity: 'common',
        value: 5,
        description: 'Couro bruto de animais.',
        stackable: true
    },
    {
        id: 'glycerin',
        name: 'Glicerina',
        type: 'Material',
        rarity: 'common',
        value: 10,
        description: 'Reagente alquímico básico.',
        stackable: true
    },
    {
        id: 'cloth',
        name: 'Tecido',
        type: 'Material',
        rarity: 'common',
        value: 3,
        description: 'Pano simples.',
        stackable: true
    },
    {
        id: 'rune_stone',
        name: 'Pedra Rúnica',
        type: 'Material',
        rarity: 'uncommon',
        value: 25,
        description: 'Pedra inscrita com símbolos arcanos.',
        stackable: true
    },
    {
        id: 'pelt',
        name: 'Pele de Animal',
        type: 'Material',
        rarity: 'common',
        value: 8,
        description: 'Pele grossa de lobo.',
        stackable: true
    },
    {
        id: 'tooth',
        name: 'Dente Afiado',
        type: 'Material',
        rarity: 'common',
        value: 3,
        description: 'Dente de predador.',
        stackable: true
    },
    {
        id: 'spectral_essence',
        name: 'Essência Espectral',
        type: 'Material',
        rarity: 'uncommon',
        value: 40,
        description: 'Fragmento de energia fantasmagórica.',
        stackable: true
    },
    {
        id: 'arrow',
        name: 'Flechas',
        type: 'Material',
        rarity: 'common',
        value: 1,
        description: 'Munição para arcos.',
        stackable: true
    }
];

// ===== GEMS & TREASURES (Gemas e Tesouros de Mineração) =====
const GEMS = [
    {
        id: 'geode_common',
        name: 'Geodo Bruto',
        type: 'Material',
        rarity: 'uncommon',
        value: 50,
        description: 'Uma pedra misteriosa. Talvez contenha algo valioso dentro.',
        stackable: true
    },
    {
        id: 'gem_chip',
        name: 'Lasca de Rubi',
        type: 'Gema',
        rarity: 'rare',
        value: 120,
        description: 'Fragmento de uma gema preciosa. Usada em encantamentos.',
        stackable: true
    },
    {
        id: 'fossil',
        name: 'Fóssil Antigo',
        type: 'Artefato',
        rarity: 'rare',
        value: 200,
        description: 'Resquício de uma era esquecida. Alquimistas pagam bem por isso.',
        stackable: true
    }
];

// ===== CURRENCY =====
const CURRENCY = [
    {
        id: 'coin',
        name: 'Moeda de Ouro',
        type: 'Moeda',
        value: 1,
        rarity: 'common',
        description: 'Cunhagem de Tristram.',
        stackable: true
    }
];

// ===== CONSOLIDATED CATALOG =====
const ITEMS_CATALOG = [
    ...WEAPONS,
    ...ARMOR,
    ...CONSUMABLES,
    ...MATERIALS,
    ...GEMS,
    ...CURRENCY
];

// ===== API FUNCTIONS =====
const ItemsDB = {
    getById: (id) => ITEMS_CATALOG.find(item => item.id === id),
    getByType: (type) => ITEMS_CATALOG.filter(item => item.type === type),
    getByRarity: (rarity) => ITEMS_CATALOG.filter(item => item.rarity === rarity),
    getBySlot: (slot) => ITEMS_CATALOG.filter(item => item.slot === slot),
    getAll: () => ITEMS_CATALOG,
    getWeapons: () => WEAPONS,
    getArmor: () => ARMOR,
    getConsumables: () => CONSUMABLES,
    getMaterials: () => MATERIALS,
    getGems: () => GEMS,
    search: (query) => ITEMS_CATALOG.filter(item => 
        item.name.toLowerCase().includes(query.toLowerCase()) ||
        item.description?.toLowerCase().includes(query.toLowerCase())
    )
};

export default ItemsDB;
export { ITEMS_CATALOG, WEAPONS, ARMOR, CONSUMABLES, MATERIALS, GEMS };

